---

- name: add new chocolatey internal source
  win_chocolatey_source:
    name: '{{ choco_ext_repo_name }}'
    state: present
    source: '{{ choco_ext_repo_source }}'

- name: install onec platform {{ v8version }}
  win_chocolatey:
    name: 1c
    version: '{{ v8version }}'
    architecture: '{{ onec_architecture }}'
    params: '{{ onec_install_params }}'
    force: '{{ reinstall }}'
    allow_multiple: yes
  register: onec_install_result

- debug:
    var: onec_install_result
    verbosity: 1

- include: iis.yml
  when: >
    server_type == "iis" and 
    update_web_config and 
    prev_v8version is defined

- include: apache.yml
  when: > 
    server_type == "apache" and
    update_web_config and 
    prev_v8version is defined
