---
- name: reg regmsc
  hosts: onecservers
  vars:
      #v8version: '8.3.18.1483'
      bin_path: 'C:\Program Files\1cv8\{{ v8version }}\bin'
  tasks:

    - name: create ansible temp directory
      win_file:
        path: '{{ ansible_win_temp_dir }}'
        state: directory
        ignore_errors: true

    - name: run script
      win_shell: 'Invoke-Item "{{ bin_path }}\RegMSC.cmd"'
      become: yes
      become_method: runas
