---
- name: deploy configuration repository server
  hosts: configreposervers
  vars_files: 
    - secrets.yml
  pre_tasks:
    - name: create ansible temp directory
      win_file:
        path: '{{ ansible_win_temp_dir }}'
        state: directory
        ignore_errors: true
  roles:
    - role: onec-configrepo-server
