---
- name: deploy onec on user term
  hosts: onecuserterms
  vars_files: 
    - secrets.yml
  pre_tasks:
    - name: create ansible temp directory
      win_file:
        path: '{{ ansible_win_temp_dir }}'
        state: directory
        ignore_errors: true
  roles:
    - role: onec-userterm
      #v8version: "8.3.18.1483"
